# [!!] please revise this where nesessary.
database:
  image: mysql
  user: docker
  password: docker
  dbname: homestreaming
redis:
  size: 10
  network: tcp
  host: redis
  port: 6379
  password: rpLKtm4jlLotK6Ng0ink3BOd
  keyPair: 2NbOAtB6szIqFugkpXAdk3iGYk0guZne