settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: app
  path: .
  commands:
    install:
      status: true
      method: go build -o app
    run:
      status: true
      method: ./app
  watcher:
    extensions:
    - go
    - tmpl
    - yaml
    - css
    - js
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
